### ISSUE TITLE
Add way (or clearer way) to quote posts

### ISSUE THREAD

**Issue by snoozbuster** [pantaloons/4charm#9]
Tapping on a post number opens it in the parallel viewer, but there's no easy way to quote that post in a reply. It seems like tapping reply in that context or tapping the header at the top should open reply with that post quoted. Or, tapping on the post number should open reply with the post quoted, and tap+hold could open it in the viewer. That would let you quote multiple posts pretty easily.

**Comment by pantaloons** [comment]
You can quote posts by tapping on them when the partial reply box is opened.

**Comment by snoozbuster** [comment]
I must be doing something wrong, because that just seems to replace the partial reply box with the post you tapped on... The partial reply box is the one in the top half of the screen, right?

**Comment by pantaloons** [comment]
It sounds like you are tapping on the post number in the top right corner, rather than the body area of the post you want to reply to.

**Comment by snoozbuster** [comment]
Aha, I see. That's not what I'd have expected, given the interface of the website itself. Thanks for the information though, sorry to bother you!
